"""Add work orders and production management

Revision ID: 002
Revises: 001
Create Date: 2025-01-08 20:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create work_orders table
    op.create_table('work_orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('work_order_number', sa.String(length=50), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('product_type', sa.String(length=100), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('cup_size', sa.String(length=20), nullable=True),
        sa.Column('cup_type', sa.String(length=50), nullable=True),
        sa.Column('material', sa.String(length=50), nullable=True),
        sa.Column('color', sa.String(length=30), nullable=True),
        sa.Column('design_specifications', sa.Text(), nullable=True),
        sa.Column('printing_requirements', sa.Text(), nullable=True),
        sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='priority'), nullable=True),
        sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'IN_PRODUCTION', 'PRODUCTION_COMPLETE', 'QUALITY_CHECK', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'ON_HOLD', name='workorderstatus'), nullable=True),
        sa.Column('order_date', sa.DateTime(), nullable=True),
        sa.Column('requested_delivery_date', sa.DateTime(), nullable=True),
        sa.Column('scheduled_production_date', sa.DateTime(), nullable=True),
        sa.Column('actual_production_start', sa.DateTime(), nullable=True),
        sa.Column('actual_production_complete', sa.DateTime(), nullable=True),
        sa.Column('estimated_ship_date', sa.DateTime(), nullable=True),
        sa.Column('actual_ship_date', sa.DateTime(), nullable=True),
        sa.Column('delivery_date', sa.DateTime(), nullable=True),
        sa.Column('production_notes', sa.Text(), nullable=True),
        sa.Column('quality_check_notes', sa.Text(), nullable=True),
        sa.Column('shipping_notes', sa.Text(), nullable=True),
        sa.Column('special_instructions', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('work_order_number')
    )
    op.create_index(op.f('ix_work_orders_customer_id'), 'work_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_number'), 'work_orders', ['work_order_number'], unique=False)

    # Create work_order_updates table for audit trail
    op.create_table('work_order_updates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('work_order_id', sa.Integer(), nullable=False),
        sa.Column('old_status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'IN_PRODUCTION', 'PRODUCTION_COMPLETE', 'QUALITY_CHECK', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'ON_HOLD', name='workorderstatus'), nullable=True),
        sa.Column('new_status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'IN_PRODUCTION', 'PRODUCTION_COMPLETE', 'QUALITY_CHECK', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'ON_HOLD', name='workorderstatus'), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_updates_id'), 'work_order_updates', ['id'], unique=False)
    op.create_index(op.f('ix_work_order_updates_work_order_id'), 'work_order_updates', ['work_order_id'], unique=False)

    # Create production_schedule table
    op.create_table('production_schedule',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('work_order_id', sa.Integer(), nullable=False),
        sa.Column('scheduled_start', sa.DateTime(), nullable=False),
        sa.Column('scheduled_end', sa.DateTime(), nullable=False),
        sa.Column('actual_start', sa.DateTime(), nullable=True),
        sa.Column('actual_end', sa.DateTime(), nullable=True),
        sa.Column('production_line', sa.String(length=50), nullable=True),
        sa.Column('machine_assigned', sa.String(length=100), nullable=True),
        sa.Column('operator_assigned', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_schedule_id'), 'production_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_production_schedule_work_order_id'), 'production_schedule', ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_schedule_work_order_id'), table_name='production_schedule')
    op.drop_index(op.f('ix_production_schedule_id'), table_name='production_schedule')
    op.drop_table('production_schedule')
    op.drop_index(op.f('ix_work_order_updates_work_order_id'), table_name='work_order_updates')
    op.drop_index(op.f('ix_work_order_updates_id'), table_name='work_order_updates')
    op.drop_table('work_order_updates')
    op.drop_index(op.f('ix_work_orders_work_order_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_customer_id'), table_name='work_orders')
    op.drop_table('work_orders')
    # ### end Alembic commands ###