"""Add simple work order system

Revision ID: 003
Revises: 002
Create Date: 2025-01-08 20:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create simple_work_orders table
    op.create_table('simple_work_orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_name', sa.String(length=200), nullable=False),
        sa.Column('customer_email', sa.String(length=200), nullable=False),
        sa.Column('customer_phone', sa.String(length=50), nullable=True),
        sa.Column('order_description', sa.Text(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('delivery_date', sa.DateTime(), nullable=True),
        sa.Column('special_notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('assigned_to', sa.String(length=100), nullable=True),
        sa.Column('assigned_at', sa.DateTime(), nullable=True),
        sa.Column('logo_file_path', sa.String(length=500), nullable=True),
        sa.Column('design_file_path', sa.String(length=500), nullable=True),
        sa.Column('other_files', sa.Text(), nullable=True),
        sa.Column('last_notification', sa.DateTime(), nullable=True),
        sa.Column('order_creator_notified', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_work_orders_id'), 'simple_work_orders', ['id'], unique=False)

    # Create work_order_files table
    op.create_table('work_order_files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('work_order_id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(length=200), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_type', sa.String(length=50), nullable=False),
        sa.Column('uploaded_by', sa.String(length=100), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['work_order_id'], ['simple_work_orders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_files_id'), 'work_order_files', ['id'], unique=False)
    op.create_index(op.f('ix_work_order_files_work_order_id'), 'work_order_files', ['work_order_id'], unique=False)

    # Create work_order_updates table
    op.create_table('work_order_updates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('work_order_id', sa.Integer(), nullable=False),
        sa.Column('old_status', sa.String(length=50), nullable=True),
        sa.Column('new_status', sa.String(length=50), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['work_order_id'], ['simple_work_orders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_updates_id'), 'work_order_updates', ['id'], unique=False)
    op.create_index(op.f('ix_work_order_updates_work_order_id'), 'work_order_updates', ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_updates_work_order_id'), table_name='work_order_updates')
    op.drop_index(op.f('ix_work_order_updates_id'), table_name='work_order_updates')
    op.drop_table('work_order_updates')
    op.drop_index(op.f('ix_work_order_files_work_order_id'), table_name='work_order_files')
    op.drop_index(op.f('ix_work_order_files_id'), table_name='work_order_files')
    op.drop_table('work_order_files')
    op.drop_index(op.f('ix_simple_work_orders_id'), table_name='simple_work_orders')
    op.drop_table('simple_work_orders')
    # ### end Alembic commands ###