"""Create simple_user table

Revision ID: 004
Revises: 003
Create Date: 2025-01-08 21:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create simple_users table
    op.create_table('simple_users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('full_name', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_users_id'), 'simple_users', ['id'], unique=False)
    op.create_index(op.f('ix_simple_users_username'), 'simple_users', ['username'], unique=True)
    op.create_index(op.f('ix_simple_users_email'), 'simple_users', ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simple_users_email'), table_name='simple_users')
    op.drop_index(op.f('ix_simple_users_username'), table_name='simple_users')
    op.drop_index(op.f('ix_simple_users_id'), table_name='simple_users')
    op.drop_table('simple_users')
    # ### end Alembic commands ###